### ISSUE TITLE
`[:host]` enforced for `Timber.Events.HTTPServerRequestEvent`?

### ISSUE THREAD

**Issue by russmatney** [timberio/timber-elixir#111]
I'm seeing the following issue when my app starts up:

```
...
the following keys must also be given when building struct Timber.Events.HTTPServerRequestEvent: [:host]
...
```

It looks like the keys for using this struct were recently enforced - we weren't setting a host before.

This seems like a misconfiguration on my part, but I'm having trouble figuring out what changed and is causing the new issue. Is there documentation anywhere around configuring this?

**Comment by DavidAntaramian** [comment]
@russmatney I'm going to assign Ben to this since he's handled the design of the schema and what's required. This may have been an internal control error where there should have been a minor release instead of patch release to prevent situations like this.

**Comment by binarylogic** [comment]
Hey @russmatney thanks for reporting this. Do you mind if I ask where you guys are building this struct? Because Timber handles this automatically with our [`EventPlug`](https://github.com/timberio/timber-elixir/blob/master/lib/timber/integrations/event_plug.ex). My guess is that you aren't using `Plug` and adding this manually? If so, my apologies, @DavidAntaramian is correct, we should have done a minor bump instead of a patch.

**Comment by binarylogic** [comment]
@russmatney we released a patch update that resolves this. Sorry for the inconvenience, please let us know if we can do anything else.

**Comment by russmatney** [comment]
Fantastic, sorry for the lack of a response/delay - got caught up with other things this week. I'll update and let you know if there are any other issues (along with our configs)!
