### ISSUE TITLE
Ecto "slow query" logging might not be working.

### ISSUE THREAD

**Issue by Trevoke** [timberio/timber-elixir#199]
I have a plain phoenix app on 1.3 which I just upgraded to timber 2.5.0.

The config directory looks like this:

```emacs
  /Users/phoenix/src/exeq/saga/config:
  total used in directory 8 available 4292894324
  drwxr-xr-x  8 phoenix staff  272 08-06 10:46 .
  drwxr-xr-x 16 phoenix staff  544 08-06 10:49 ..
  -rw-r--r--  1 phoenix staff 1447 08-02 11:42 config.exs
  -rw-r--r--  1 phoenix staff 1570 08-02 11:42 dev.exs
  -rw-r--r--  1 phoenix staff 2199 08-06 10:46 prod.exs
  -rw-r--r--  1 phoenix staff  668 07-24 13:56 test.exs
  -rw-r--r--  1 phoenix staff 1436 07-25 15:15 timber.exs
```

This is the bottom of `config.exs`:

```elixir
# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env}.exs"

# Import Timber, structured logging
import_config "timber.exs"
```

This is what I have put in my `prod.exs`:

```elixir
config :timber, Timber.Integrations.EctoLogger,
  query_time_ms_threshold: 2_000 # 2 seconds
```

I just copied this from the PR message :  https://github.com/timberio/timber-elixir/pull/198#issue-247580906 because, well, two seconds works well for me right now.

I expected that, since that file gets loaded before the Timber config file does, I should be fine.. And yet if I load a REPL in my prod system, I see:

```elixir
iex(saga@127.0.0.1)3> Application.get_env :timber, :query_time_ms_threshold
nil
```

... My guess is that there's something up with what the code is doing here: https://github.com/timberio/timber-elixir/blob/master/lib/timber/integrations/ecto_logger.ex#L124  - `defp config, do: Elixir.Application.get_env(:odin_aws, __MODULE__, [])`

**Comment by binarylogic** [comment]
😮 , thanks for reporting. I just updated that method to use the proper configuration namespace. If you update to `2.5.1` all should work as expected.

**Comment by Trevoke** [comment]
Yep! We're golden. And you're welcome, of course. Since I'd requested the feature, the least I can do is help out a little.

**Comment by binarylogic** [comment]
Nice. Yep, we're using it internally as well. I'm thinking if the threshold is set and surpassed, a level of `warn` might be more appropriate? We keep a pretty close eye on our error / warn levels, this would give slower queries higher visibility. I'm curious what you're thoughts are on that.

**Comment by Trevoke** [comment]
I'm writing some things here based on my thoughts, in relative ignorance of Timber's mission / vision, so take it with a grain of salt.

To answer your question directly, if that is something you're thinking about, I would let the user choose the log level. 
I hesitate to attach something like a "log level" (error, warn, info, debug) to a slow query, as it is technically part of the system, but also ... I think a somewhat orthogonal need?

**Which is to say, if I filter by log level such as `warn`, I wouldn't expect to see slow queries.**

If I'm running a stress test, I'll probably see a lot of them; I don't need to have them marked as `warn` or even `errors`. 

I see value in being able to see these queries easily (which Timber already provides).
I would see value in being able to map them / graph them, to see when they occur, see if there is a pattern, as it would help with the spelunking.

Does Timber handle "custom" log levels? Marking those as "slow_queries" or "slow", and giving them the same log level as warning, might be nice. Although it creates the additional headache of, how would you filter "all the warning types" ? 

This is about the end of my wordable thoughts on the topic for now, I hope it gives you something to chew on. I've got more thoughts but they're still wordless. I'll let you know when there's words. :)

**Comment by DavidAntaramian** [comment]
@Trevoke This depends on how you're classifying a "slow query." The `warn` level indicates "this is atypical but should not affect system consistency." The `error` level indicates "there was a logical failure, system consistency may be affected, operator intervention suggested."

We don't currently handle "custom" log levels at the package level; we typically rely on the underlying system to define log levels (in this case, the `Logger` app).

Looking at this, though, you probably want to keep slow queries at the `info` level, since it seems that you don't view slow queries as atypical but informative. In other words, they're something you want to know about so you can improve performance in your system.

Also, since these will be the only SQL logs in your application, filtering by the sql_query event will be enough to see just your slow queries. We have a graphing feature on our roadmap that will work using the same filters and allow you to graph attached metadata. I think when we release that, it will be powerful addition to your analysis process.

**Comment by Trevoke** [comment]
I think you understand my perspective and current needs very well :)
