### ISSUE TITLE
Hot upgrade fails on Hackney 1.11.0

### ISSUE THREAD

**Issue by darksheik** [timberio/timber-elixir#252]
Another dependency (AppSignal) updated our `hackney` library to `1.11.0`, and it seems to have caused an issue with hot upgrades and Timber `2.6.1`.  We received the following message in the log, and we don't think the upgrade fully completed:

```
16:26:37.662 [error] :gen_event handler Timber.LoggerBackends.HTTP installed at Logger
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :undefined
        (hackney) /home/ubuntu/edeliver/deps/hackney/src/hackney_connect.erl:69: :hackney_connect.create_connection/5
        (hackney) /home/ubuntu/edeliver/deps/hackney/src/hackney_connect.erl:37: :hackney_connect.connect/5
        (hackney) /home/ubuntu/edeliver/deps/hackney/src/hackney.erl:315: :hackney.request/5
        (timber) lib/timber/logger_backends/http.ex:332: Timber.LoggerBackends.HTTP.issue_request/1
        (timber) lib/timber/logger_backends/http.ex:175: Timber.LoggerBackends.HTTP.handle_info/2
        (stdlib) gen_event.erl:573: :gen_event.server_update/4
        (stdlib) gen_event.erl:555: :gen_event.server_notify/4
        (stdlib) gen_event.erl:343: :gen_event.handle_msg/6
```

**Comment by binarylogic** [comment]
Hey @darksheik thanks for reporting. Just to get a little more info:

1. Any particular reason `hackney` was updated? In order for `1.11.0` to be used you would need to force override it via `override: true` when adding it as a dependency.
2. I don't see `:hackney` as a dependency on the App Signal library.

We're cautious with raising the version on `:hackney` because it's rare that it ever goes smoothly, it almost also has bugs. We generally try to follow the lead of [ExAws](https://github.com/ex-aws/ex_aws) since it's based on hackney and has a good base of users.

**Comment by darksheik** [comment]
AppSignal uses `httpoison`, which uses `hackney`.
It looks like we can revert to `1.10.1` hackney though.  AppSignal only needs httpoison `0.11.0`.

**Comment by binarylogic** [comment]
Ah ok. I'd like to run a few tests on `1.11.0` before we bump the version. Otherwise `1.10.1` should work fine. Another option is to override the dependency explicitly in your `mix.exs` file:

```
{:hackney, "~> 1.11.0", override: true}
```

This will override the `timber` dependency requirement.

**Comment by binarylogic** [comment]
@darksheik going to close this with the above workaround. Let me know if you have any other problems.
