### ISSUE TITLE
Send pre-flight request on HTTP initialization

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-elixir#95]
This ensures that HTTP is working properly

**Comment by DavidAntaramian** [comment]
@binarylogic Do you want this to be on application load? That should be fairly easy. The question I have is whether you want to raise and shut down the client application. We've discussed this previously, and I believe the consensus was that we should raise because we won't be able to send logs, and there is no other way to provide feedback to the user since we run into a logging Catch-22.

**Comment by binarylogic** [comment]
Yep, I agree, it should perform the checks and raise if it is not successful. If the IODevice failed wouldn't it crash their app? I think we should do the same thing.

**Comment by DavidAntaramian** [comment]
Hmm, how would IODevice fail?
